{-# LANGUAGE OverloadedStrings #-}
module LHC.Prim where
import CompactString
baseBuiltins :: [CompactString]
baseBuiltins = [
    "*#"
  , "*##"
  , "+#"
  , "+##"
  , "-#"
  , "-##"
  , "/##"
  , "/=#"
  , "<#"
  , "<##"
  , "<=#"
  , "<=##"
  , "==#"
  , "==##"
  , ">#"
  , ">##"
  , ">=#"
  , ">=##"
  , "Addr#"
  , "Array#"
  , "BCO#"
  , "ByteArray#"
  , "Char#"
  , "Double#"
  , "Float#"
  , "Int#"
  , "MVar#"
  , "MutVar#"
  , "MutableArray#"
  , "MutableByteArray#"
  , "StableName#"
  , "StablePtr#"
  , "State#"
  , "TVar#"
  , "ThreadId#"
  , "Weak#"
  , "Word#"
  , "acosDouble#"
  , "acosFloat#"
  , "addr2Int#"
  , "and#"
  , "asinDouble#"
  , "asinFloat#"
  , "atanDouble#"
  , "atanFloat#"
  , "byteArrayContents#"
  , "chr#"
  , "cmpInteger#"
  , "cmpIntegerInt#"
  , "cosDouble#"
  , "cosFloat#"
  , "coshDouble#"
  , "coshFloat#"
  , "dataToTag#"
  , "delay#"
  , "divideFloat#"
  , "double2Float#"
  , "double2Int#"
  , "eqAddr#"
  , "eqChar#"
  , "eqFloat#"
  , "eqStableName#"
  , "eqStablePtr#"
  , "eqWord#"
  , "expDouble#"
  , "expFloat#"
  , "float2Double#"
  , "float2Int#"
  , "gcdInt#"
  , "gcdIntegerInt#"
  , "geAddr#"
  , "geChar#"
  , "geFloat#"
  , "geWord#"
  , "gtAddr#"
  , "gtChar#"
  , "gtFloat#"
  , "gtWord#"
  , "indexAddrArray#"
  , "indexAddrOffAddr#"
  , "indexCharArray#"
  , "indexCharOffAddr#"
  , "indexDoubleArray#"
  , "indexDoubleOffAddr#"
  , "indexFloatArray#"
  , "indexFloatOffAddr#"
  , "indexInt16Array#"
  , "indexInt16OffAddr#"
  , "indexInt32Array#"
  , "indexInt32OffAddr#"
  , "indexInt64Array#"
  , "indexInt64OffAddr#"
  , "indexInt8Array#"
  , "indexInt8OffAddr#"
  , "indexIntArray#"
  , "indexIntOffAddr#"
  , "indexStablePtrArray#"
  , "indexStablePtrOffAddr#"
  , "indexWideCharArray#"
  , "indexWideCharOffAddr#"
  , "indexWord16Array#"
  , "indexWord16OffAddr#"
  , "indexWord32Array#"
  , "indexWord32OffAddr#"
  , "indexWord64Array#"
  , "indexWord64OffAddr#"
  , "indexWord8Array#"
  , "indexWord8OffAddr#"
  , "indexWordArray#"
  , "indexWordOffAddr#"
  , "int2Addr#"
  , "int2Double#"
  , "int2Float#"
  , "int2Word#"
  , "integer2Int#"
  , "integer2Word#"
  , "killThread#"
  , "labelThread#"
  , "leAddr#"
  , "leChar#"
  , "leFloat#"
  , "leWord#"
  , "logDouble#"
  , "logFloat#"
  , "ltAddr#"
  , "ltChar#"
  , "ltFloat#"
  , "ltWord#"
  , "minusAddr#"
  , "minusFloat#"
  , "minusWord#"
  , "mulIntMayOflo#"
  , "narrow16Int#"
  , "narrow16Word#"
  , "narrow32Int#"
  , "narrow32Word#"
  , "narrow8Int#"
  , "narrow8Word#"
  , "neAddr#"
  , "neChar#"
  , "neFloat#"
  , "neWord#"
  , "negateDouble#"
  , "negateFloat#"
  , "negateInt#"
  , "noDuplicate#"
  , "not#"
  , "nullAddr#"
  , "or#"
  , "ord#"
  , "par#"
  , "parAt#"
  , "parAtAbs#"
  , "parAtForNow#"
  , "parAtRel#"
  , "parGlobal#"
  , "parLocal#"
  , "plusAddr#"
  , "plusFloat#"
  , "plusWord#"
  , "powerFloat#"
  , "putMVar#"
  , "quotInt#"
  , "quotWord#"
  , "realWorld#"
  , "reallyUnsafePtrEquality#"
  , "remAddr#"
  , "remInt#"
  , "remWord#"
  , "sameMVar#"
  , "sameMutVar#"
  , "sameMutableArray#"
  , "sameMutableByteArray#"
  , "sameTVar#"
  , "sinDouble#"
  , "sinFloat#"
  , "sinhDouble#"
  , "sinhFloat#"
  , "sizeofByteArray#"
  , "sizeofMutableByteArray#"
  , "sqrtDouble#"
  , "sqrtFloat#"
  , "stableNameToInt#"
  , "tagToEnum#"
  , "tanDouble#"
  , "tanFloat#"
  , "tanhDouble#"
  , "tanhFloat#"
  , "timesFloat#"
  , "timesWord#"
  , "touch#"
  , "uncheckedIShiftL#"
  , "uncheckedIShiftRA#"
  , "uncheckedIShiftRL#"
  , "uncheckedShiftL#"
  , "uncheckedShiftRL#"
  , "unsafeCoerce#"
  , "waitRead#"
  , "waitWrite#"
  , "word2Int#"
  , "writeAddrArray#"
  , "writeAddrOffAddr#"
  , "writeCharArray#"
  , "writeCharOffAddr#"
  , "writeDoubleArray#"
  , "writeDoubleOffAddr#"
  , "writeFloatArray#"
  , "writeFloatOffAddr#"
  , "writeInt16Array#"
  , "writeInt16OffAddr#"
  , "writeInt32Array#"
  , "writeInt32OffAddr#"
  , "writeInt64Array#"
  , "writeInt64OffAddr#"
  , "writeInt8Array#"
  , "writeInt8OffAddr#"
  , "writeIntArray#"
  , "writeIntOffAddr#"
  , "writeMutVar#"
  , "writeStablePtrArray#"
  , "writeStablePtrOffAddr#"
  , "writeWideCharArray#"
  , "writeWideCharOffAddr#"
  , "writeWord16Array#"
  , "writeWord16OffAddr#"
  , "writeWord32Array#"
  , "writeWord32OffAddr#"
  , "writeWord64Array#"
  , "writeWord64OffAddr#"
  , "writeWord8Array#"
  , "writeWord8OffAddr#"
  , "writeWordArray#"
  , "writeWordOffAddr#"
  , "xor#"
  , "yield#"
  ]
vectorBuiltins :: [CompactString]
vectorBuiltins = [
    "addIntC#"
  , "addrToHValue#"
  , "andInteger#"
  , "asyncExceptionsBlocked#"
  , "catch#"
  , "catchRetry#"
  , "catchSTM#"
  , "check#"
  , "complementInteger#"
  , "deRefWeak#"
  , "decodeDouble#"
  , "decodeDouble_2Int#"
  , "decodeFloat#"
  , "decodeFloat_Int#"
  , "divExactInteger#"
  , "divModInteger#"
  , "finalizeWeak#"
  , "forkOn#"
  , "gcdInteger#"
  , "getApStackVal#"
  , "int2Integer#"
  , "isCurrentThreadBound#"
  , "isEmptyMVar#"
  , "makeStableName#"
  , "minusInteger#"
  , "mkApUpd0#"
  , "mkWeak#"
  , "mkWeakForeignEnv#"
  , "myThreadId#"
  , "newAlignedPinnedByteArray#"
  , "newBCO#"
  , "newByteArray#"
  , "newMVar#"
  , "newMutVar#"
  , "newPinnedByteArray#"
  , "newTVar#"
  , "orInteger#"
  , "plusInteger#"
  , "quotInteger#"
  , "quotRemInteger#"
  , "readAddrArray#"
  , "readAddrOffAddr#"
  , "readCharArray#"
  , "readCharOffAddr#"
  , "readDoubleArray#"
  , "readDoubleOffAddr#"
  , "readFloatArray#"
  , "readFloatOffAddr#"
  , "readInt16Array#"
  , "readInt16OffAddr#"
  , "readInt32Array#"
  , "readInt32OffAddr#"
  , "readInt64Array#"
  , "readInt64OffAddr#"
  , "readInt8Array#"
  , "readInt8OffAddr#"
  , "readIntArray#"
  , "readIntOffAddr#"
  , "readMutVar#"
  , "readStablePtrArray#"
  , "readStablePtrOffAddr#"
  , "readTVar#"
  , "readWideCharArray#"
  , "readWideCharOffAddr#"
  , "readWord16Array#"
  , "readWord16OffAddr#"
  , "readWord32Array#"
  , "readWord32OffAddr#"
  , "readWord64Array#"
  , "readWord64OffAddr#"
  , "readWord8Array#"
  , "readWord8OffAddr#"
  , "readWordArray#"
  , "readWordOffAddr#"
  , "remInteger#"
  , "retry#"
  , "subIntC#"
  , "takeMVar#"
  , "threadStatus#"
  , "timesInteger#"
  , "tryPutMVar#"
  , "tryTakeMVar#"
  , "unpackClosure#"
  , "unsafeFreezeByteArray#"
  , "unsafeThawArray#"
  , "word2Integer#"
  , "xorInteger#"
  ]
unsupportedBuiltins :: [CompactString]
unsupportedBuiltins = [
    "atomicModifyMutVar#"
  , "atomically#"
  , "fork#"
  , "raise#"
  , "raiseIO#"
  , "writeTVar#"
  ]
{- ORIGINAL DEFINITIONS
baseBuiltins        = ["<#",">#","<=#",">=#","-#","+#","*#","narrow32Int#"
                      ,"uncheckedIShiftRA#","and#","==#", "remInt#", "noDuplicate#"
                      ,"narrow8Word#", "writeInt8OffAddr#", "writeWord8OffAddr#"
                      ,"narrow8Int#", "byteArrayContents#","touch#"
                      ,"uncheckedIShiftL#", "negateInt#", "not#"
                      ,"indexCharOffAddr#","minusWord#","geWord#","eqWord#","narrow16Word#"
                      ,"neWord#", "ltWord#", "gtWord#", "remWord#"
                      ,"ord#","chr#","or#","narrow32Word#","uncheckedShiftL#","plusWord#"
                      ,"uncheckedShiftRL#","neChar#","narrow16Int#","timesWord#"
                      ,"writeAddrOffAddr#","writeInt32OffAddr#","quotInt#", "quotWord#"
                      ,"writeDoubleOffAddr#"
                      ,"readWord32OffAddr#"
                      ,"writeWord32OffAddr#"
                      ,"waitRead#"
                      ,"leWord#","/=#","writeCharArray#","xor#", "realWorld#"
                      ,"waitWrite#", "negateDouble#", "negateFloat#", "sqrtDouble#", "expDouble#", "**##"
                      ,"sinDouble#", "tanDouble#", "cosDouble#", "asinDouble#", "atanDouble#"
                      ,"acosDouble#", "asinhDouble#", "sinhDouble#", "tanhDouble#", "coshDouble#"
                      ,"<##", "==##", ">##", "<=##", ">=##", "-##", "+##", "*##", "/##"
                      ,"ltFloat#", "eqFloat#", "writeWord8Array#"
                      ,"coerceDoubleToWord", "coerceWordToDouble", "logDouble#", "int2Double#", "double2Int#"
                      ,"int2Float#", "divideFloat#", "timesFloat#", "minusFloat#", "plusFloat#"
                      ,"gtFloat#", "geFloat#", "leFloat#", "sqrtFloat#" ]
vectorBuiltins      = ["unsafeFreezeByteArray#", "newAlignedPinnedByteArray#"
                      , "word2Integer#","integer2Int#", "newByteArray#", "newPinnedByteArray#"
                      ,"readInt8OffAddr#","readInt32OffAddr#","readAddrOffAddr#","readInt32OffAddr#"
                      ,"readWord8Array#", "readDoubleOffAddr#", "writeDoubleOffAddr#"
                      ,"mkWeak#", "readCharArray#"]
unsupportedBuiltins = ["raise#","atomicModifyMutVar#","writeTVar#"
                      ,"raiseIO#","fork#","atomically#"]
-}
